# Exercise 3

**Please Note**: We updated the requirements.txt

Please install the new requirements before editing this exercise.

## Import packages

In [3]:
import os
from vll.utils.download import download_mnist
import numpy as np
import matplotlib.pyplot as plt
import skimage
import skimage.io
import torch
import torch.nn.functional as F
from torchvision import transforms
from models.mnist.simple_cnn import Net

## Task 1
(2 points)

In this task, you will learn some basic tensor operations using the PyTorch library.

Reference for torch: https://pytorch.org/docs/stable/torch.html

In [4]:
# Create a numpy array that looks like this: [0, 1, 2, ..., 19]
array = np.arange(20)
# Convert the numpy array to a torch tensor
tensor = torch.from_numpy(array)
print(tensor)

# Create a tensor that contains random numbers.
# It should have the same size like the numpy array.
# Multiply it with the previous tensor.
tensor = tensor.to(dtype=torch.float)
rand_tensor = torch.randn_like(tensor)
result = tensor * rand_tensor
print("tensor * rand_tensor = {}".format(result))

# Create a tensor that contains only 1s.
# It should have the same size like the numpy array.
# Substract it from the previous tensor.
tensor_of_1s = torch.ones_like(tensor)
result2 = result - tensor_of_1s
print(result2)

# Get the 5th element using a index.
element = result2[4]
print(element)

# Create a tensor that contains only 0s.
# It should have the same size like the numpy array.
# Multiply it with the previous tensor without any assignment (in place).
tensor_of_0s = torch.zeros_like(tensor)
tensor_of_0s = result2 * tensor_of_0s
print(tensor_of_0s)


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
tensor * rand_tensor = tensor([  0.0000,  -1.2604,  -2.2272,  -4.8489,  -3.0661,   0.8845,  -5.3310,
          1.2062, -18.8656,  -1.5230,  -7.9432,  -4.4752,  10.9575,  12.2400,
        -31.6328,  -1.7950, -16.7057,   2.2841,   1.2904,  20.5180])
tensor([ -1.0000,  -2.2604,  -3.2272,  -5.8489,  -4.0661,  -0.1155,  -6.3310,
          0.2062, -19.8656,  -2.5230,  -8.9432,  -5.4752,   9.9575,  11.2400,
        -32.6328,  -2.7950, -17.7057,   1.2841,   0.2904,  19.5180])
tensor(-4.0661)
tensor([-0., -0., -0., -0., -0., -0., -0., 0., -0., -0., -0., -0., 0., 0., -0., -0., -0., 0., 0., 0.])


In [6]:
# Load the image from the last exercise as RGB image.

rgb_img = skimage.io.imread('./data/pepo.jpg')

# Convert the image to a tensor
img_tensor = torch.from_numpy(np.array(rgb_img))
#print("Image tensor is : {}".format(img_tensor))

# Print its shape
print(img_tensor.shape)

# Flatten the image
flattened_img_tensor = img_tensor.reshape(-1)

print(len(flattened_img_tensor))

# Add another dimension resulting in a 1x78643 tensor
expanded_img_tensor = flattened_img_tensor.unsqueeze(0)

print(expanded_img_tensor.shape)

# Revert the last action
squeezed_img_tensor = expanded_img_tensor.squeeze()
print(squeezed_img_tensor.shape)

# Reshape the tensor, so that it has the original 2D dimensions
original_shape = img_tensor.shape
image = squeezed_img_tensor.reshape(original_shape) 
print(image.shape)

# Calculate the sum, mean and max of the tensor
print(torch.sum(image))
print(torch.mean(image))
print(torch.max(image))

: 

: 

## Task 2
(2 points)

Use Autograd to perform operations on a tensor and output then gradients.

In [ ]:
# Create a random 2x2 tensor which requires gradients
x = 
print(x)

# Create another tensor by adding 2.0
y = 
print(y)

# Create a third tensor z = y^2
z = 
print(z)

# Compute out as the mean of values in z
out = 
print(out)

# Perform back propagation on out


# Print the gradients dout/dx


# Create a copy of y whithout gradients
y2 = 
print(y2.requires_grad)

# Perform the mean operation on z
# with gradients globally disabled


## Task 3
(3 points)

Implement a Dataset class for MNIST.

In [ ]:
# We first download the MNIST dataset
download_mnist()

In [ ]:
class MNIST:
    """
    Dataset class for MNIST
    """

    def __init__(self, root, transform=None):
        """
        root -- path to either "training" or "testing"
        
        transform -- transform (from torchvision.transforms)
                     to be applied to the data
        """
        # save transforms
        self.transform = transform
        
        # TODO: create a list of all subdirectories (named like the classes) 
        #       within the dataset root
        
        
        # TODO: create a list of paths to all images
        #       with the ground truth label
        
    
    def __len__(self):
        """
        Returns the lenght of the dataset (number of images)
        """
        # TODO: return the length (number of images) of the dataset
        

    def __getitem__(self, index):
        """
        Loads and returns one image as floating point numpy array
        
        index -- image index in [0, self.__len__() - 1]
        """
        # TODO: load the ith image as an numpy array (dtype=float32)
        
        
        # TODO: apply transforms to the image (if there are any)
        
        
        # TODO: return a tuple (transformed image, ground truth)
       

## Task 4
(3 points)

You can now load a pretrained neural network model we provide.
Your last task is to run the model on the MNIST test dataset, plot some example images with the predicted labels and compute the prediction accuracy.

In [ ]:
def validate(model, data_loader):
    # TODO: Create a 10x10 grid of subplots
   
    
    model.eval()
    correct = 0 # count for correct predictions
    
    with torch.no_grad():
        for i, item in enumerate(data_loader):
            # TODO: unpack item into image and ground truth
            #       and run network on them
            
            
            # TODO: get class with highest probability
            
            
            # TODO: check if prediction is correct
            #       and add it to correct count
            
            
            # plot the first 100 images
            if i < 100:
                # TODO: compute position of ith image in the grid
                
                
                # TODO: convert image tensor to numpy array
                #       and normalize to [0, 1]
                
                
                # TODO: make wrongly predicted images red
                
                
                # TODO: disable axis and show image
                
                
                # TODO: show the predicted class next to each image
                
            
            elif i == 100:
                plt.show()
    
    # TODO: compute and print the prediction accuracy in percent
    

# create a DataLoader using the implemented MNIST dataset class
data_loader = torch.utils.data.DataLoader(
    MNIST('data/mnist/testing',
    transform=transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.1307,), (0.3081,))
    ])),
    batch_size=1, shuffle=True)

# create the neural network
model = Net()

# load the statedict from 'models/mnist/simple_cnn.pt'
model.load_state_dict(torch.load('models/mnist/simple_cnn.pt'))

# validate the model
validate(model, data_loader)